"""create UserVault

Revision ID: fdf62002eaf1
Revises: 38965a37ca08
Create Date: 2025-11-06 13:19:52.013930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf62002eaf1'
down_revision: Union[str, Sequence[str], None] = '38965a37ca08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_vaults',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_method', sa.String(), nullable=True),
    sa.Column('amount', sa.String(), nullable=True),
    sa.Column('vault_address', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_method'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_vaults_id'), 'user_vaults', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vaults_id'), table_name='user_vaults')
    op.drop_table('user_vaults')
    # ### end Alembic commands ###
